-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Author"
(
    "Full_name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Author_pkey" PRIMARY KEY ("Full_name")
);

CREATE TABLE IF NOT EXISTS public."book"
(
    "author" text COLLATE pg_catalog."default" NOT NULL,
    "name" text COLLATE pg_catalog."default" NOT NULL,
    "genre" text COLLATE pg_catalog."default" NOT NULL,
    "value" integer NOT NULL,
    book_id integer NOT NULL,
    CONSTRAINT "book_pkey" PRIMARY KEY (book_id)
);

CREATE TABLE IF NOT EXISTS public."reader"
(
    "full_name" text COLLATE pg_catalog."default" NOT NULL,
    "basket" integer,
    CONSTRAINT "reader_pkey" PRIMARY KEY ("full_name")
);

CREATE TABLE IF NOT EXISTS public.genre
(
    "name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT genre_pkey PRIMARY KEY ("name")
);

ALTER TABLE IF EXISTS public."book"
    ADD CONSTRAINT author_fk FOREIGN KEY ("author")
    REFERENCES public."author " ("full_name") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."book"
    ADD CONSTRAINT genre_fk FOREIGN KEY ("genre")
    REFERENCES public.genre ("name") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."reader"
    ADD CONSTRAINT "basket_fk" FOREIGN KEY ("basket")
    REFERENCES public."book" (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "basket"
    ON public."reader"("basket");


ALTER TABLE IF EXISTS public."reader"
    ADD CONSTRAINT "basket_fk2" FOREIGN KEY ("basket")
    REFERENCES public."book" ("value") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "basket"
    ON public."reader"("basket");

END;